# Generated by Django 4.2.4 on 2023-09-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_clubs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CLUBS',
            new_name='CLUB',
        ),
    ]
