# Generated by Django 4.2.4 on 2023-11-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='Image',
            field=models.ImageField(default='static/user.png', upload_to=None),
        ),
    ]
