# Generated by Django 4.2.4 on 2023-09-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLUBS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('Student_ID', models.CharField(blank=True, max_length=20)),
                ('Student_Mail', models.CharField(blank=True, max_length=50)),
                ('Phone_Number', models.CharField(blank=True, max_length=20)),
                ('Preferred_Club', models.CharField(blank=True, max_length=100)),
                ('Reason_behind_joinning_club', models.TextField(blank=True, max_length=2000)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
