# Generated by Django 4.2.4 on 2023-10-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_club_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='Image',
            field=models.ImageField(default='user.png', upload_to=None),
        ),
    ]
